### ISSUE TITLE
Limit handler run time and non-response retries

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli-java-plugin#15]
Although Lambda currently allows for 15minutes of execution runtime, the main instance in which a handler should ever need to execute beyond a timeframe of seconds would be to perform post-action stabilization.

The Lambda wrapper already caters for re-execution with handler-specified context, and this is the correct way to perform long-running checks (like stabilization).

To mitigate risks associated with arbitrary compute, the following limits need to be put in place;

1) limit the underlying handlers runtime to **60seconds** maximum, before the wrapper forcibly terminates execution and schedules a retry, using the initial context
2) limit the number of such "no-response" terminations to **3** before the handler request is failed
3) emit events/metrics for the above 
4) create a CloudWatch alarm in the hosting account to indicate that the retry limit has been breached. In a managed environment, CloudFormation may choose to use this alarm to blacklist a misbehaving handler package
5) as well, in the managed environment, CloudFormation may limit the overall runtime and concurrent requests of a handler to mitigate against unbounded compute risks

The intention is that handler developers are encouraged to reduce the amount of compute time their handler requires, and take advantage of the baked retry mechanism to perform long-running stabilization runs.

**NOTE**: the numbers above are arbitrary and small, since it’s harder to rein them in later. Typically speaking, a handler operation should be very quick, with long running execution expressed as a stabilization period.

**Comment by ammokhov** [comment]
closing as it has been implemented
