### ISSUE TITLE
"integer" type in schema cannot be generated in POJO as a "long"

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli-java-plugin#151]
The code generation for POJO uses `integer` for any `{ "type": "integer" }` in the schema. There is no way to make this a long instead without disabling codegen and manipulating the POJO directly. Would be good to either document the workaround or make it easier for developers to tweak the generated POJO somehow.

**Comment by bkabrda** [comment]
Hey folks, is there any progress on this? We (maintainers of https://github.com/DataDog/datadog-cloudformation-resources) would very much like to see this. Right now we're marking the fields that need to be generated as `Long` with `number`, which generates them as `Double`. This unfortunately poses some problems, as explained in [1]. We have a user who posted a PR to instead use strings [2], which works better, but is still just a workaround for the inability to have long integers. For us, the solution proposed in #244 works fine (as long as "Physical ID" would just be a number, e.g. `123456789` and not end with `L`, e.g. `123456789L`, which would pose the same set of problems as reported in [1]).

Thanks!

[1] https://github.com/DataDog/datadog-cloudformation-resources/issues/80
[2] https://github.com/DataDog/datadog-cloudformation-resources/pull/81

**Comment by jotompki** [comment]
Should be addressed by #328.  Will close once released.

**Comment by jotompki** [comment]
Released in https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/releases/tag/v2.0.3-plugin
