### ISSUE TITLE
injectCredentialsAndInvoke doesn't support void returns.

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli-java-plugin#176]
e.g; an API call to `setBucketNotificationConfiguration` for S3 returns void, hence the proxy call cannot support this API.

**Comment by jotompki** [comment]
Should just need to add a void version of the method here: https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/AmazonWebServicesClientProxy.java?

**Comment by ammokhov** [comment]
so since aws sdk v2 has different model it always returns a response, so the change needs to be made in here - https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/AmazonWebServicesClientProxy.java#L439-L455
