### ISSUE TITLE
Sensitive data should not be logged

### ISSUE THREAD

**Issue by divyansh-gupta** [aws-cloudformation/cloudformation-cli-java-plugin#221]
I am developing a resource and have placed a property in the resource schema `writeOnlyProperties` category. This marks the property as sensitive. However, the property value is still logged when the Handler is run.

This is where the logging is happening: https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/CloudFormationCallbackAdapter.java#L81-L82

Sensitive data like this should not be logged. Would appreciate a fix, let me know if I can provide more information. Thanks!

**Comment by jotompki** [comment]
Change is merged in. Going to leave this open until we release a new version to maven which includes changes

**Comment by jotompki** [comment]
Released to maven. Closing out
