### ISSUE TITLE
Add message from cause object to the Cfn Exception messages where acceptable.

### ISSUE THREAD

**Issue by priyap286** [aws-cloudformation/cloudformation-cli-java-plugin#230]
It would be helpful if message from the cause object are added to the Cfn exception objects generated. 

I feel this would be at least helpful in the case of [CfnInvalidRequestException](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/exceptions/CfnInvalidRequestException.java). Currently, the user would not know which property resulted in this exception even if the cause object has that information as the message from the cause object is not incorporated in the <code>CfnInvalidRequestException</code> object generated. 

The <code>BaseHandlerException</code> class uses [this constructor](https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html#RuntimeException(java.lang.String,%20java.lang.Throwable)) of <code>RuntimeException</code> which does not incorporate the message from the cause object.

**Comment by tobywf** [comment]
We'd have to get this right, so that internal information or e.g. write-only properties are not accidentally captured. Hence, this is a manual process for now.

**Comment by ammokhov** [comment]
closing as this is addressed by this [code](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/AmazonWebServicesClientProxy.java#L575)
