### ISSUE TITLE
generateResourceIdentifier should take stack name

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-cli-java-plugin#239]
Existing CloudFormation resources, when not given an explicit name, use the pattern `{StackName}-{LogicalId}-{RandomSuffix}`. This is useful as it helps users easily find resources corresponding to a given stack among many resources created by identical templates (e.g., they all have the same logical id but are in different stacks). The utility function provided in the Java plugin, [`generateResourceIdentifier`](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/86babd0a576407976fe9569449b1b860664bb775/src/main/java/software/amazon/cloudformation/resource/IdentifierUtils.java#L47), takes logical id. There should be a version that takes stack name as well. Users *could* just pass in the logical id as `{StackName}-{LogicalId}`, but a) they may not think to do so, and b) this prevents the method from smartly trimming down these values in the face of length constraints, which CloudFormation usually does.

**Comment by ammokhov** [comment]
closing this issue as being tracked in #299
