### ISSUE TITLE
Cfn error code exceptions do not use error messages from the cause exception, omitting service level error messages and request Ids

### ISSUE THREAD

**Issue by aygold92** [aws-cloudformation/cloudformation-cli-java-plugin#243]
We created exceptions to represent the different error codes, specifically:

* CfnAccessDeniedException
* CfnAlreadyExistsException
* CfnGeneralServiceException
* CfnInternalFailureException
* CfnInvalidCredentialsException
* CfnInvalidRequestException
* CfnNetworkFailureException
* CfnNotFoundException
* CfnNotStabilizedException
* CfnNotUpdatableException
* CfnResourceConflictException
* CfnServiceInternalErrorException
* CfnServiceLimitExceededException
* CfnThrottlingException

The idea is that the handler would throw this exception, and the java plugin would convert that to a ProgressEvent with a FAILED status.  However, these exceptions do not take error messages, which is required when there is a FAILED ProgressEvent.  

Also, these exceptions should extend a common `BaseErrorCodeException` or somehting like that, so we can easily catch this.  Handlers should not be throwing any other type of exception from their code.

Lastly, NotFound and AlreadyExists have duplicate exceptions, and I'm not sure what they are for:
* ResourceNotFoundException and CfnNotFoundException
* ResourceAlreadyExistsException and CfnAlreadyExistsException

**Comment by aygold92** [comment]
After doing a bit of digging it looks like we actually should use exception messages https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/ddfbcbf34fc04b7b4ca63656be67e2514092598a/src/main/java/software/amazon/cloudformation/proxy/ExceptionMessages.java#L17, but the constructors are pretty confusing and these messages never include AWS requestIds.

**Comment by aygold92** [comment]
it also looks we use BaseHandlerException which includes the ErrorCode https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/ddfbcbf34fc04b7b4ca63656be67e2514092598a/src/main/java/software/amazon/cloudformation/exceptions/BaseHandlerException.java#L20

**Comment by aygold92** [comment]
it looks like really what the work is:
1. remove `TerminalException` https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/exceptions/TerminalException.java, which is not used anywhere and is confusing, 
1. remove `ResourceAlreadyExistsException` and `ResourceNotFoundException` which are duplicates
1. improve exception messages from the `BaseHandlerException`s to include AWS error messages/requestIds

**Comment by PatMyron** [comment]
> Lastly, NotFound and AlreadyExists have duplicate exceptions, and I'm not sure what they are for:
> 
> * ResourceNotFoundException and CfnNotFoundException
> * ResourceAlreadyExistsException and CfnAlreadyExistsException

looks like these should be deprecated to avoid conflicts:

https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/1dd595a016f2071180203ab299aa415c6f17b04d/src/main/java/software/amazon/cloudformation/exceptions/ResourceNotFoundException.java#L18-L21

https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/1dd595a016f2071180203ab299aa415c6f17b04d/src/main/java/software/amazon/cloudformation/exceptions/ResourceAlreadyExistsException.java#L18-L21

**Comment by wbingli** [comment]
hmm, this issue should be fixed by https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/264

**Comment by ammokhov** [comment]
closing this issue as has been fixed by #264
