### ISSUE TITLE
Unreliable unit test

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli-java-plugin#245]
I observe an unreliable test when run locally;

```
> mvn package install
...
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.697 s <<< FAILURE! - in software.amazon.cloudformation.proxy.DelayTest
[ERROR] fixedDelay  Time elapsed: 0.379 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: execution exceeded timeout of 300 ms by 55 ms
...
```

Second attempt passed. Assume it's because there's a time component to this test, maybe we can mock the clock?

**Comment by ammokhov** [comment]
@rjlohan which handler this test is for?

**Comment by rjlohan** [comment]
I didn't actually capture that sorry. I thought it was just a CallChain test issue, didn't realise it would be handler specific.

**Comment by ammokhov** [comment]
closing this issue
