### ISSUE TITLE
Validate resource before deserialize into resource model

### ISSUE THREAD

**Issue by wbingli** [aws-cloudformation/cloudformation-cli-java-plugin#273]
As for now,  Java plugin will deserialize the raw resource property into resource model before validation. 

If the resource property is an invalid structure, e.g. pass a String but schema requires a List, it will fail sadly. And CloudFormation will show `Internal Failure` for this resource.

If validate resource before deserialize it, it can validate such invalid resource properly.

**Comment by rjlohan** [comment]
Before making changes here, verify the history of the serialization behaviour. e.g;

* https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/commit/5e7fe4ea2163347923cbb9eff4c5d899e05fc050#diff-f71d0cfe4773c081286e31b592b040ff

* https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/commit/7f221a22f1e00a037ccd36f8e357e729c7880280#diff-f71d0cfe4773c081286e31b592b040ff

Validating the raw JSON can produce other errors, or fail with false negatives if it's not ordered correctly.

**Comment by wbingli** [comment]
> Before making changes here, verify the history of the serialization behaviour. e.g;
> 
> * [5e7fe4e#diff-f71d0cfe4773c081286e31b592b040ff](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/commit/5e7fe4ea2163347923cbb9eff4c5d899e05fc050#diff-f71d0cfe4773c081286e31b592b040ff)
> * [7f221a2#diff-f71d0cfe4773c081286e31b592b040ff](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/commit/7f221a22f1e00a037ccd36f8e357e729c7880280#diff-f71d0cfe4773c081286e31b592b040ff)
> 
> Validating the raw JSON can produce other errors, or fail with false negatives if it's not ordered correctly.

The PR #274 do consider for such case.  It will only try to catch `MismatchedInputException` if the first deserialization fails due to mismatch type.   This avoid the false negative for the stringifier issue but provide useful information if type mismatch.

The following validation is kept as-is so that it will validate based on the converted resource model.

**Comment by wbingli** [comment]
Resolving as the fix is merged.
