### ISSUE TITLE
"maven dependency not found in pom.xml" when defined in parent pom

### ISSUE THREAD

**Issue by bkabrda** [aws-cloudformation/cloudformation-cli-java-plugin#282]
Hey folks,
we have a pom.xml setup in our CF resources [1] where we defined the plugin as a dependency in a parent pom.xml and then inherit from this parent pom in all our individual resource poms. After trying to upgrade to:

```
cloudformation-cli             0.1.4
cloudformation-cli-java-plugin 2.0.0
```

we're seeing this error when trying to `mvn package`: `[2020-07-03T07:35:43Z] CRITICAL - 'aws-cloudformation-rpdk-java-plugin' maven dependency not found in pom.xml.`. I've been through the code and it looks like the `_get_java_plugin_dependency_version` doesn't account for pom inheritance. Could this be fixed? Is there a temporary workaround that we could use?

[1] https://github.com/DataDog/datadog-cloudformation-resources/

**Comment by wbingli** [comment]
Thanks for reporting this issue.

The temporary workaround would be adding the aws-cloudformation-rpdk-java-plugin maven dependency to each of the resource pom.xml.

We are working to fix this issue.

**Comment by wbingli** [comment]
This issue resolved in https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/295

**Comment by ammokhov** [comment]
closing this as been resolved
