### ISSUE TITLE
Provide `StackId` in the ResourceHandlerRequest

### ISSUE THREAD

**Issue by wbingli** [aws-cloudformation/cloudformation-cli-java-plugin#299]
StackId is useful information for the resource to get context. Also some resources uses stackId to generate name with stack name.

Current workaround is [using system tags](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/blob/master/aws-logs-loggroup/src/main/java/software/amazon/logs/loggroup/CreateHandler.java#L69). However, this information should be directly provided as public method in `ResourceHandlerRequest` to the handler.

**Comment by ammokhov** [comment]
tracking #239 in here
