### ISSUE TITLE
Understanding the Resource Provider input schema

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [aws-cloudformation/cloudformation-cli-java-plugin#322]
I am looking at some of the recently open sourced Cloudformation resource providers and it seems that they use a [LambdaWrapper]() for the test invocations. Couple wrapper functions down, [processInvocation](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/AbstractWrapper.java#L278) get's called.

Looking at the code,

https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/4bdae6ec8d27543fa0ca9a4d50515cdf325ad953/src/main/java/software/amazon/cloudformation/AbstractWrapper.java#L274-L281

It appears that the input stream is not formatted like a cloudformation template and furthermore is only handling one resource at a time.

1. What is the input schema for the `handleRequest` function

https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/4bdae6ec8d27543fa0ca9a4d50515cdf325ad953/src/main/java/software/amazon/cloudformation/LambdaWrapper.java#L53-L56

2. If this truly is only handling one resource at a time, where is the looping and ordering of resources handled? Is that code open sourced?

**Comment by ammokhov** [comment]
@aidan-plenert-macdonald this class is the wrapper around resource providers handlers and live on the client side rather than backend. All handlers are isolated per resource and dont have access to any other providers implementations. Dependency evaluation is not open sourced
